# build data map

In [5]:
%cd ..

e:\projects of camp\X_Ray_class

In [ ]:
import pandas as pd
from glob import glob
import os
from pathlib import Path

In [10]:
import pandas as pd
from glob import glob
import os
from pathlib import Path


def build_data_map(folder_path):
    imgs_paths = glob(os.path.join(folder_path, "*.jpeg"))
    clas = Path(folder_path).name
    split = Path(folder_path).parent.name
    return pd.DataFrame({
        "imgs": imgs_paths,
        "clas": clas,
        "split": split
    })

test_normal = build_data_map(r"E:\projects\Chest X-Ray\load_data\chest_xray\chest_xray\test\NORMAL")
test_pneumonia = build_data_map(r"E:\projects\Chest X-Ray\load_data\chest_xray\chest_xray\test\PNEUMONIA")

train_normal = build_data_map(r"E:\projects\Chest X-Ray\load_data\chest_xray\chest_xray\train\NORMAL")
train_pneumonia = build_data_map(r"E:\projects\Chest X-Ray\load_data\chest_xray\chest_xray\train\PNEUMONIA")

val_normal = build_data_map(r"E:\projects\Chest X-Ray\load_data\chest_xray\chest_xray\val\NORMAL")
val_pneumonia = build_data_map(r"E:\projects\Chest X-Ray\load_data\chest_xray\chest_xray\val\PNEUMONIA")

In [13]:
val_normal

                                                imgs    clas split
0  E:\projects\Chest X-Ray\load_data\chest_xray\c...  NORMAL   val
1  E:\projects\Chest X-Ray\load_data\chest_xray\c...  NORMAL   val
2  E:\projects\Chest X-Ray\load_data\chest_xray\c...  NORMAL   val
3  E:\projects\Chest X-Ray\load_data\chest_xray\c...  NORMAL   val
4  E:\projects\Chest X-Ray\load_data\chest_xray\c...  NORMAL   val
5  E:\projects\Chest X-Ray\load_data\chest_xray\c...  NORMAL   val
6  E:\projects\Chest X-Ray\load_data\chest_xray\c...  NORMAL   val
7  E:\projects\Chest X-Ray\load_data\chest_xray\c...  NORMAL   val

In [14]:
train_pneumonia

                                                   imgs       clas  split
0     E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA  train
1     E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA  train
2     E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA  train
3     E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA  train
4     E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA  train
...                                                 ...        ...    ...
3870  E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA  train
3871  E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA  train
3872  E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA  train
3873  E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA  train
3874  E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA  train

[3875 rows x 3 columns]

In [15]:
data1 = pd.concat([
    test_normal,
    test_pneumonia,
    train_normal,
    train_pneumonia,
    val_normal,
    val_pneumonia
], ignore_index=True)

In [16]:
data1

                                                   imgs       clas split
0     E:\projects\Chest X-Ray\load_data\chest_xray\c...     NORMAL  test
1     E:\projects\Chest X-Ray\load_data\chest_xray\c...     NORMAL  test
2     E:\projects\Chest X-Ray\load_data\chest_xray\c...     NORMAL  test
3     E:\projects\Chest X-Ray\load_data\chest_xray\c...     NORMAL  test
4     E:\projects\Chest X-Ray\load_data\chest_xray\c...     NORMAL  test
...                                                 ...        ...   ...
5851  E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA   val
5852  E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA   val
5853  E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA   val
5854  E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA   val
5855  E:\projects\Chest X-Ray\load_data\chest_xray\c...  PNEUMONIA   val

[5856 rows x 3 columns]

# EDA

In [12]:
WIDTH = 224
HEIGHT = 224

In [ ]:

for i,row in data1.iterrows():
    img_path = row["imgs_path"]
    img=Image.open(img_path)
    resized_img = img.resize((WIDTH, HEIGHT))

: